from enum import Enum

class WorkflowStatus(Enum):
    RECEIVED = 'RECEIVED'
    VALIDATED = 'VALIDATED'
    RESOLVED_SCENARIO = 'RESOLVED_SCENARIO'
    STARTING ='STARTING'
    RUNNING ='RUNNING'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'
    RETRYING = 'RETRYING'

class ErrorCode(Enum):
    VALIDATION_ERROR = 'VALIDATION_ERROR'
    TEMPORAL_START_ERROR = 'TEMPORAL_START_ERROR'
    TEMPORAL_EXECUTION_ERROR = 'TEMPORAL_EXECUTION_ERROR'