FROM python:3.11-slim-bullseye

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

COPY requirements-listener.txt ./
RUN pip install --no-cache-dir -r requirements-listener.txt

COPY . .

ENV PYTHONPATH=/app

CMD ["python", "main.py"]
