services:
  postgres_app:
    image: postgres:16
    container_name: postgres_app
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${PGAPP_DB_NAME}
      - POSTGRES_USER=${PGAPP_DB_USER}
      - POSTGRES_PASSWORD=${PGAPP_DB_PASSWORD}
    ports:
      - "${PGAPP_DB_PORT}:5432"
    volumes:
      - ${PGAPP_DB_VOLUME}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app_db"]
      interval: 30s
      timeout: 5s
      retries: 10

  postgres_temporal:
    image: postgres:16
    container_name: postgres_temporal
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${PGT_DB_NAME}
      - POSTGRES_USER=${PGT_DB_USER}
      - POSTGRES_PASSWORD=${PGT_DB_PASSWORD}
    ports:
      - "${PGT_DB_PORT}:5432"
    volumes:
      - ${PGT_DB_VOLUME}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d temporal"]
      interval: 30s
      timeout: 5s
      retries: 10

  temporal:
    image: temporalio/auto-setup:latest
    container_name: temporal
    restart: unless-stopped
    depends_on:
      postgres_temporal:
        condition: service_healthy
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_SEEDS=postgres_temporal
      - POSTGRES_USER=${PGT_DB_USER}
      - POSTGRES_PWD=${PGT_DB_PASSWORD}
      - DBNAME=${PGT_DB_NAME}
      - VISIBILITY_DBNAME=temporal_visibility
      - DEFAULT_NAMESPACE=${TMP_DEFAULT_NAMESPACE}
      - DEFAULT_NAMESPACE_RETENTION=168h
      - SKIP_SCHEMA_SETUP=false
      - LOG_LEVEL=info
    ports:
      - "${TEMPORAL_PORT}:7233"

  temporal-ui:
    image: temporalio/ui:latest
    container_name: temporal-ui
    restart: unless-stopped
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_DEFAULT_NAMESPACE=default
    ports:
      - "${TEMPORAL_UI_PORT}:8080"

  seaweed-master:
    image: chrislusf/seaweedfs:latest
    container_name: seaweed-master
    command: master -ip=seaweed-master -port=9333
    ports:
      - "${SEAWEED_MASTER_PORT}:9333"
    volumes:
      - ${SEAWEED_DATA_PATH}/master:/data

  seaweed-volume:
    image: chrislusf/seaweedfs:latest
    container_name: seaweed-volume
    command: volume -mserver="seaweed-master:9333" -port=8080 -ip=seaweed-volume -dir=/data
    depends_on:
      - seaweed-master
    ports:
      - "${SEAWEED_VOLUME_PORT}:8080"
    volumes:
      - ${SEAWEED_DATA_PATH}/volume:/data

  seaweed-filer:
    image: chrislusf/seaweedfs:latest
    container_name: seaweed-filer
    command: filer -master="seaweed-master:9333" -ip=seaweed-filer -port=8888
    depends_on:
      - seaweed-master
      - seaweed-volume
    ports:
      - "${SEAWEED_FILER_PORT}:8888"
    volumes:
      - ${SEAWEED_DATA_PATH}/filer:/data

  seaweed-s3:
    image: chrislusf/seaweedfs:latest
    container_name: seaweed-s3
    command: s3 -filer="seaweed-filer:8888" -port=8333
    depends_on:
      - seaweed-filer
    ports:
      - "${SEAWEED_S3_PORT}:8333"
  
  portainer:
      image: portainer/portainer-ce:latest
      container_name: portainer
      ports:
        - "${PORTAINER_PORT}:9443"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ${PD_DATA_PATH}:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  keydb:
    image: eqalpha/keydb:latest
    container_name: keydb
    ports:
      - "6379:6379"
    command: keydb-server --requirepass password --appendonly yes

  point-cloud-listener:
    image: code.pepega.club/4ereshkin/clod:v1.0
    container_name: point-cloud-listener
    restart: unless-stopped
    env_file: .env
    environment:
      - TEMPORAL_DSN=temporal:7233
      - KEYDB_DSN=redis://:password@keydb:6379
      - RABBIT_DSN=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - temporal
      - keydb
      - rabbitmq
    command: python main.py

  worker-ingest:
    image: code.pepega.club/4ereshkin/clod:v1.0
    container_name: worker-ingest
    restart: unless-stopped
    env_file: .env
    environment:
      - TEMPORAL_DSN=temporal:7233
      - KEYDB_DSN=redis://:password@keydb:6379
      - RABBIT_DSN=amqp://guest:guest@rabbitmq:5672/
      - S3_ENDPOINT=http://seaweed-s3:8333
    depends_on:
      - temporal
      - keydb
      - seaweed-s3
      - rabbitmq
    command: python point_cloud/workers/worker_ingest.py

  worker-registration:
    image: code.pepega.club/4ereshkin/clod:v1.0
    container_name: worker-registration
    restart: unless-stopped
    env_file: .env
    environment:
      - TEMPORAL_DSN=temporal:7233
      - KEYDB_DSN=redis://:password@keydb:6379
      - RABBIT_DSN=amqp://guest:guest@rabbitmq:5672/
      - S3_ENDPOINT=http://seaweed-s3:8333
    depends_on:
      - temporal
      - keydb
      - seaweed-s3
      - rabbitmq
    command: python point_cloud/workers/worker_registration.py